In [1]:
# Building Convolutional Neural Network Algorithm

In [2]:
# Step-1 Create Convolutional Layers
from keras.models import Sequential
from keras.layers import Convolution2D

cnn=Sequential()
cnn.add(Convolution2D(32,3,3,input_shape=(64,64,3),activation='relu'))
'''
  32=No.of Feature Map Layers after applying feature detector (or) No.of filter or future detectors applying to input layer.
  3,3= Shape of the feature map layer row*column (or) shape of the feature detector in row*column
  input_shape= We are rescaling all input values to 64 *64 in 3 layers(red,green,Blue)'''

Using TensorFlow backend.


C:\Users\arunkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., activation="relu")`
  


'\n  32=No.of Feature Map Layers after applying feature detector (or) No.of filter or future detectors applying to input layer.\n  3,3= Shape of the feature map layer row*column (or) shape of the feature detector in row*column\n  input_shape= We are rescaling all input values to 64 *64 in 3 layers(red,green,Blue)'

In [4]:
# Step -2 Create Polling Layers
from keras.layers import MaxPooling2D

cnn.add(MaxPooling2D(pool_size=(2,2)))
'''pool_size= Pooling size after convolution layer. We are applying max value for each 2*2 values in convolution layer'''

# Create Second convolution layer to get better accuracy for test set
cnn.add(Convolution2D(32,3,3,activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2,2)))

C:\Users\arunkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
  


In [5]:
# Step-3 Create flatten to pooled layer
from keras.layers import Flatten
cnn.add(Flatten())
'''No Need to customize any parameters it will convert pooled layers to flatten layers'''

'No Need to customize any parameters it will convert pooled layers to flatten layers'

In [6]:
# Step-4 Fully Connection Layer
from keras.layers import Dense
# First Fully connected hidden layer
cnn.add(Dense(output_dim=128,activation='relu'))
# Second Fully Connected hidden layer
cnn.add(Dense(output_dim=128,activation='relu'))
# Output layer
cnn.add(Dense(output_dim=1,activation='sigmoid'))
# Compile the CNN
cnn.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

C:\Users\arunkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`
  after removing the cwd from sys.path.
C:\Users\arunkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`
  
C:\Users\arunkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [9]:
# Fitting the CNN to the images
# We used Image aqumentation code from keras documention
# Image Aqumentation to provent overfitting the training data and which cause less accuracy for test set.

from keras.preprocessing.image import ImageDataGenerator
'''ImageAqumentation is used to split the dataset into folds and each fold it will keep reuse the existing data using flip 
   and compress image so that it can learn all feature better'''

# It will re scale the training data from different scale to same scale
train_datagen=ImageDataGenerator(rescale=1./255,
                                shear_range=0.2,
                                zoom_range=0.2,
                                horizontal_flip=True)
# Re-scale test set data from different scale to same scale
test_datagen=ImageDataGenerator(rescale=1./255)

# Locating the training set folder 

training_set=train_datagen.flow_from_directory('dataset/training_set',
                                               # Target size should match with input_dim of convolution layer
                                              target_size=(64,64),
                                              batch_size=32,
                                              class_mode='binary')
# Locating the test set fold

test_set=test_datagen.flow_from_directory('dataset/test_set',
                                         target_size=(64,64),
                                         batch_size=32,
                                         class_mode='binary')

# Generating the predictions

cnn.fit_generator(training_set,
                  # training set data size
                 samples_per_epoch=8000,
                 nb_epoch=25,
                 validation_data=test_set,
                 nb_val_samples=2000)

Found 8000 images belonging to 2 classes.
Found 2000 images belonging to 2 classes.


C:\Users\arunkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:38: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
C:\Users\arunkumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:38: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras_pre..., validation_data=<keras_pre..., steps_per_epoch=250, epochs=25, validation_steps=2000)`





Epoch 1/25





250/250 [==============================] - 197s 787ms/step - loss: 0.6714 - acc: 0.5729 - val_loss: 0.6269 - val_acc: 0.6584
Epoch 2/25
250/250 [==============================] - 145s 582ms/step - loss: 0.6032 - acc: 0.6747 - val_loss: 0.5606 - val_acc: 0.7163
Epoch 3/25
250/250 [==============================] - 148s 592ms/step - loss: 0.5491 - acc: 0.7201 - val_loss: 0.5275 - val_acc: 0.7336
Epoch 4/25
250/250 [==============================] - 145s 580ms/step - loss: 0.5216 - acc: 0.7371 - val_loss: 0.5289 - val_acc: 0.7346
Epoch 5/25
250/250 [==============================] - 145s 581ms/step - loss: 0.4983 - acc: 0.7531 - val_loss: 0.4894 - val_acc: 0.7629
Epoch 6/25
250/250 [==============================] - 150s 599ms/step - loss: 0.4733 - acc: 0.7723 - val_loss: 0.4995 - val_acc: 0.7612
Epoch 7/25
250/250 [==============================] - 147s 587ms/step - loss: 0.4548 - acc: 0.7893 - val_loss: 0.4691 - val_acc: 0.7804
Epoch 8/25
250/250 [====================

In [10]:
# We got 90.04% accuracy for training set and 79.43% accuracy for test set.

In [11]:
# Make single prediction observation

import numpy as np
from keras.preprocessing import image
test_image=image.load_img('dataset/single_prediction/cat_or_dog_1.jpg',target_size=(64,64))
# convert the image to array 
test_image=image.img_to_array(test_image)
print("---- convert image to array-------")
print(test_image)
# error  when checking expected to have 4 dimensions, but got array  with shape(64,64,3)
# Adding one more axis to handle error
test_image=np.expand_dims(test_image,axis=0)
result=cnn.predict(test_image)
print(result)
print(training_set.class_indices)

---- convert image to array-------
[[[ 54.  58.   7.]
  [ 58.  63.   9.]
  [ 64.  67.  10.]
  ...
  [136. 144.  71.]
  [140. 150.  77.]
  [139. 149.  78.]]

 [[ 48.  54.   6.]
  [ 51.  58.   7.]
  [ 58.  63.   9.]
  ...
  [129. 137.  64.]
  [139. 149.  78.]
  [141. 151.  80.]]

 [[ 48.  56.   7.]
  [ 48.  56.   7.]
  [ 54.  61.  10.]
  ...
  [123. 130.  63.]
  [136. 145.  80.]
  [140. 149.  82.]]

 ...

 [[ 46.  55.  12.]
  [ 42.  50.   9.]
  [ 38.  49.   9.]
  ...
  [239. 205. 170.]
  [235. 209. 186.]
  [229. 202. 173.]]

 [[ 50.  57.  15.]
  [ 42.  50.   9.]
  [ 44.  52.  11.]
  ...
  [234. 200. 162.]
  [236. 206. 178.]
  [234. 203. 174.]]

 [[ 53.  59.  13.]
  [ 43.  51.  10.]
  [ 49.  56.  12.]
  ...
  [231. 195. 159.]
  [235. 213. 190.]
  [233. 206. 179.]]]
[[1.]]
{'cats': 0, 'dogs': 1}


In [12]:
# We got correct image